# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  run-test:
    name: Testing ralfg images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON: ["cp36-cp36m"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run --rm --privileged hypriot/qemu-register
      - uses: docker://quay.io/pypa/manylinux2014_aarch64
        with: 
           args: |
                bash -c "uname -m; 
                         /opt/python/${{ matrix.PYTHON }}/bin/pip install virtualenv;
                         /opt/python/${{ matrix.PYTHON }}/bin/python -m virtualenv .venv;
                         .venv/bin/pip install setuptools wheel six;
                         REGEX='cp3([0-9])*';
                         if [[ '${{ matrix.PYTHON }}' =~ $REGEX ]]; then PY_LIMITED_API="--py-limited-api=cp3${BASH_REMATCH[1]}" fi;
                         .venv/bin/python -V;"
                         
